# Generated by Django 5.1.5 on 2025-01-28 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('note', models.TextField()),
                ('required', models.BooleanField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Text field'), ('ONE_O', 'One option'), ('MUL_O', 'Multiple options'), ('NUM', 'Number'), ('Y_N', 'Yes or No'), ('FILE', 'File field')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leh_condition', models.CharField(choices=[('>', 'higher'), ('=', 'equal'), ('<', 'lower')], max_length=1)),
                ('answer_condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.answer')),
                ('form_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relations_from', to='forms.form')),
                ('form_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relations_to', to='forms.form')),
                ('question_condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.question'),
        ),
        migrations.CreateModel(
            name='RequestWithBoolean',
            fields=[
                ('userrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.userrequest')),
                ('yes_or_no', models.BooleanField()),
            ],
            bases=('forms.userrequest',),
        ),
        migrations.CreateModel(
            name='RequestWithFile',
            fields=[
                ('userrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.userrequest')),
                ('file_url', models.CharField(max_length=255)),
            ],
            bases=('forms.userrequest',),
        ),
        migrations.CreateModel(
            name='RequestWithText',
            fields=[
                ('userrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.userrequest')),
                ('text', models.TextField()),
            ],
            bases=('forms.userrequest',),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.question'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RequestWithAnswer',
            fields=[
                ('userrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.userrequest')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.answer')),
            ],
            bases=('forms.userrequest',),
        ),
    ]
