# Generated by Django 5.1.5 on 2025-01-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestWithNumber',
            fields=[
                ('userrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.userrequest')),
                ('number', models.FloatField()),
            ],
            bases=('forms.userrequest',),
        ),
        migrations.AddField(
            model_name='form',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
