# Generated by Django 5.1.6 on 2025-02-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_answer_options_alter_form_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='user',
        ),
    ]
